name: Continuous Delivery

on:
  release:
    types: [published]

jobs:

  deploy-in-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
