name: Continuous Integration

on :
  push:
    branches:
      - main
      - dev

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm run build

  test:
    name: test
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm i  

      - name: Create a .env
        run: | 
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Launch docker db
        run: docker compose up

      - name: Generate Prisma  
        run: | 
          npx prisma generate
          npx prisma migrate dev
