name: Continuous Integration

on :
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: npm i 
      - run: npx prisma generate
      - run: npx prisma migrate dev
      - name: Echo okay
        run: echo "okay"
