name: Continuous Integration

on :
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm i 

      - name: Launch docker db
        run: docker compose up
        
      - run: npx prisma generate
      - run: npx prisma migrate dev
      - name: Echo okay
        run: echo "okay"
