name: Continuous Integration for develop

on :
  push:
    branches-ignore:
      - master
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'
      
      - name: Install packages
        run: npm ci

    #   - name: Linter
    #     run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
    

      - name: Check for existing PR
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --head develop --base main --json number -q '.[0].number' || true)
          echo "existing_pr_number=$PR_EXISTS" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Pull Request 
        if: steps.check_pr.outputs.existing_pr_number == ''
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pull } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: context.build.source,
              head: context.build.source,
              base: 'develop',
              body: 'This PR was automatically generated by the CI/CD pipeline to merge recent changes from  ' + context.build.source + ' into `develop` for release. Please review and merge.',
              // draft: true, 
            });
            console.log(`Created pull request: ${pull.html_url}`);
          github-token: ${{ secrets.GITHUB_TOKEN }}

